Repository TDycores-Project/TDycore, pull requests merged in 2020-09, with the labels that each got.

#73 Fixed bug by initializing mesh filename to zero when creating DM
  src/tdydm.c
Labels: bug-fix

#75 Added some stuff to the README.
  README.md
Labels: documentation

#78 Neumann boundary condition and two-point flux in MPFA-O
  demo/transient/transient-mpfaof90-neumann.regression.gold
  demo/transient/transient-mpfaof90-tpf-neumann.regression.gold
  demo/transient/transient-mpfaof90-tpf.regression.gold
  demo/transient/transient-snes-mpfaof90-transect-neumann.regression.gold
  demo/transient/transient-snes-mpfaof90.regression.gold
  demo/transient/transient_mpfaof90.cfg
  demo/transient/transient_snes_mpfaof90.F90
  demo/transient/transient_snes_mpfaof90.cfg
  include/private/tdycoreimpl.h
  include/private/tdymeshimpl.h
  include/private/tdymeshutilsimpl.h
  include/private/tdyutils.h
  include/tdycore.h
  share/meshes/transect_44x1x3_hex_uniform_dz_mesh.exo
  src/interface/ftn/tdycoref.c
  src/mesh/tdycoremesh.c
  src/mesh/tdycoremeshutils.c
  src/mpfao/3D/tdympfao3D_core.c
  src/tdycore.c
  src/tdyeos.c
  src/tdyutils.c
Labels: enhancement

#83 Added TDyInit, TDyFinalize, and profiling stage registry.
  demo/SPE10/steady.c
  demo/mpfao/mpfao.c
  demo/richards/richards.cfg
  demo/richards/richards_driver.c
  demo/steady/steady.c
  demo/steadyblock/steadyblock.c
  demo/steadyf90/steadyf90.F90
  demo/transient/transient.c
  demo/transient/transient_mpfao.c
  demo/transient/transient_mpfaof90.F90
  demo/transient/transient_snes_mpfaof90.F90
  demo/transient/transient_th_mpfao.c
  include/tdycore.h
  include/tdytimers.h
  src/f90-mod/tdycoremod.F90
  src/interface/ftn/tdycoref.c
  src/tdycore.c
  src/tdytimers.c
Labels: cleanup, performance

#86 MPFA-O timers: part 1
  include/tdytimers.h
  src/mpfao/3D/tdympfao3D_core.c
  src/mpfao/3D/tdympfao3D_snes.c
  src/mpfao/3D/tdympfao3D_steady.c
  src/mpfao/3D/tdympfao3D_th_ts.c
  src/mpfao/3D/tdympfao3D_ts.c
  src/mpfao/3D/tdympfao3D_ts_dae.c
  src/mpfao/3D/tdympfao3D_ts_transientvar.c
  src/mpfao/tdympfao.c
  src/tdycore.c
Labels: performance
