Repository TDycores-Project/TDycore, pull requests merged in 2020-11, with the labels that each got.

#116 Introduced a basic Doxygen/Breathe/Sphinx setup
  AUTHORS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Doxyfile
  doc/README.md
  doc/sphinx/Makefile
  doc/sphinx/requirements.txt
  doc/sphinx/source/CODE_OF_CONDUCT.md
  doc/sphinx/source/CONTRIBUTING.md
  doc/sphinx/source/conf.py
  doc/sphinx/source/development.rst
  doc/sphinx/source/gettingstarted.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/intro.rst
  doc/sphinx/source/references.bib
  doc/sphinx/source/references.rst
  doc/sphinx/source/releasenotes.rst
  doc/sphinx/source/styleguide.rst
  makefile
Labels: documentation

#122 Changed invocation of MatSetValuesLocal in 3D MPFAO TS.
  src/mpfao/3D/tdympfao3D_ts.c
Labels: cleanup, performance

#119 Rough draft of a style guide. Let the holy wars begin!
  doc/sphinx/source/styleguide.rst
Labels: documentation

#124 MPFA-O code modifications to be consistent with style guide
  demo/steady/steady.c
  include/private/tdycoreimpl.h
  include/private/tdymemoryimpl.h
  include/private/tdymeshimpl.h
  include/private/tdymeshutilsimpl.h
  include/private/tdyregionimpl.h
  include/private/tdyregressionimpl.h
  src/mesh/tdycoremesh.c
  src/mesh/tdycoremeshutils.c
  src/mpfao/2D/tdympfao2D.c
  src/mpfao/3D/tdympfao3D_core.c
  src/mpfao/3D/tdympfao3D_snes.c
  src/mpfao/3D/tdympfao3D_steady.c
  src/mpfao/3D/tdympfao3D_th_ts.c
  src/mpfao/3D/tdympfao3D_ts.c
  src/mpfao/3D/tdympfao3D_ts_dae.c
  src/mpfao/3D/tdympfao3D_ts_transientvar.c
  src/mpfao/3D/tdympfao3D_utils.c
  src/mpfao/tdympfao.c
  src/tdycore.c
  src/tdymemory.c
  src/tdympfao3D_core.c.temp
  src/tdyregression.c
Labels: cleanup
