Repository TDycores-Project/TDycore, pull requests merged in 2020-10, with the labels that each got.

#92 Minor changes for profiling, plus migrated docs.
  README.md
  src/tdycore.c
  src/tdydriver.c
Labels: documentation, performance

#94 Fixes parallel MPFA-O run
  src/mesh/tdycoremesh.c
  src/mpfao/tdympfao.c
  src/tdydm.c
Labels: bug-fix

#110 Tdyperfplot: automatic plotting of scaling studies
  demo/richards/richards_driver.c
  include/private/tdymeshimpl.h
  include/tdytimers.h
  src/mesh/tdycoremesh.c
  src/tdycore.c
  src/tdytimers.c
  tools/tdyperfplot
  tools/tdyprof
Labels: enhancement, performance, utilities
